# create a GitHub Action to Email the user when the deployment is complete

on:
  deployment_status

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment status"
          body: "Deployment ${GITHUB_DEPLOYMENT_STATUS} on ${GITHUB_REPOSITORY} is ${GITHUB_DEPLOYMENT_STATUS}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_FROM }}
          content_type: text/plain